spring:
  datasource:
    schema: classpath:db/schema-mysql.sql
    #    data: classpath:db/data-mysql.sql
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:mvcdemo
    url: jdbc:h2:./db/data/test;AUTO_SERVER=TRUE
    platform: h2

h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      web-allow-others: true
